global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration - routes fired alerts to alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: "services"
    metrics_path: /metrics
    static_configs:
      - targets: ["alert-ingestion:8001", "incident-management:8002"]

  - job_name: "mock-metrics"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8082"]
