global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'alert-ingestion'
    metrics_path: /metrics
    static_configs:
      - targets: ['alert-ingestion:8001']

  - job_name: 'incident-management'
    metrics_path: /metrics
    static_configs:
      - targets: ['incident-management:8002']

  - job_name: 'oncall-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['oncall-service:8003']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
